name: Deploy Next.js to VPS

on:
  push:
    branches:
      - main   # 🚀 Déclenché quand on push sur main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # adapte selon ton projet

      - name: Install dependencies
        run: npm install --leagacy-peer-deps

      - name: Build Next.js
        run: npm run build

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.VPS_PATH }}
            git pull origin main
            npm install --production
            npm run build
            pm2 restart jigiiyaso || pm2 start npm --name "jigiiyaso" -- run start

